### ISSUE TITLE
Bootstrap link gives 404 error

### ISSUE THREAD

**Issue by GrigorG1** [AvianNetwork/Bootstrap#1]
Hello, the latest bootstrap link gives 404 error:
https://wallet.avn.network/bootstrap/Avian.zip

Would it be possible to fix it please?

**Comment by herrye991** [comment]
Download from release, they move it to google drive https://github.com/AvianNetwork/Bootstrap/releases

**Comment by GrigorG1** [comment]
Great, thanks!
